steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - -t
  - '${_IMAGE_URI}:$COMMIT_SHA'
  - .
- name: 'gcr.io/cloud-builders/docker'
  args:
  - push
  - '${_IMAGE_URI}:$COMMIT_SHA'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: gcloud
  args:
  - run
  - deploy
  - '${_SERVICE_NAME}'
  - '--project=${_PROJECT_ID}'
  - '--region=${_RUN_REGION}'
  - '--image=${_IMAGE_URI}:$COMMIT_SHA'
  - '--platform=managed'
  - '--allow-unauthenticated'
  - '--set-env-vars=APP_MODULE=${_APP_MODULE}'
images:
- '${_IMAGE_URI}:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
