from .base import IndustryRoute

# Seeded from the legacy keywords in the original api/index.py
food_service_route = IndustryRoute(
    key="food_service",
    label="Food Service & Restaurants",
    description="Jobs in restaurants, cafes, bars, and other food preparation and service establishments.",
    search_queries=[
        "restaurant server jobs near Salt Lake City",
        "restaurant cook jobs near Salt Lake City",
        "line cook jobs near Salt Lake City",
        "prep cook jobs near Salt Lake City",
        "busser jobs restaurant near Salt Lake City",
        "food runner restaurant jobs near Salt Lake City",
        "host hostess restaurant jobs near Salt Lake City",
        "dishwasher restaurant jobs near Salt Lake City",
        "kitchen supervisor restaurant jobs near Salt Lake City",
        "barista cafe jobs near Salt Lake City",
    ],
    match_keywords={
        "restaurant", "waiter", "waitress", "server", "busser", "food runner",
        "host", "hostess", "cook", "line cook", "prep cook", "dishwasher",
        "dishwashing", "kitchen", "chef", "sous chef", "barista", "cafe",
        "coffee", "bakery", "deli", "grill", "pizza", "sandwich", "dining",
        "food service", "culinary", "catering", "expo", "steward",
        "shift lead", "shift leader", "kitchen supervisor", "biscuit",
        "drink maker", "dish machine operator",
    },
    negative_keywords={
        "software engineer", "developer", "registered nurse", "warehouse", "cdl",
        "forklift", "security guard", "mechanic", "medical assistant",
        "dental assistant", "teacher", "account executive", "sales representative",
    },
    role_families={
        "server": "front-of-house",
        "waiter": "front-of-house",
        "waitress": "front-of-house",
        "busser": "front-of-house",
        "food runner": "front-of-house",
        "host": "front-of-house",
        "hostess": "front-of-house",
        "barista": "front-of-house",
        "cashier": "front-of-house",
        "cook": "back-of-house",
        "line cook": "back-of-house",
        "prep cook": "back-of-house",
        "dishwasher": "back-of-house",
        "dishwashing": "back-of-house",
        "kitchen": "back-of-house",
        "chef": "back-of-house",
        "steward": "back-of-house",
        "supervisor": "management",
        "manager": "management",
        "director": "management",
        "lead": "management",
    },
    required_credentials=["Utah Food Handler Permit"],
)
